---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/users/:id/posts/:id/comments":
    post:
      summary: Creates a comment
      tags:
      - Comments
      parameters: []
      responses:
        '201':
          description: pet created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                post_id:
                  type: integer
                text:
                  type: string
              required:
              - user_id
              - post_id
              - text
          application/xml:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                post_id:
                  type: integer
                text:
                  type: string
              required:
              - user_id
              - post_id
              - text
    get:
      summary: Retrieves a comment
      tags:
      - Comments
      parameters:
      - user: post
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: name found
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                  post_id:
                    type: integer
                required:
                - user_id
                - post_id
            application/xml:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                  post_id:
                    type: integer
                required:
                - user_id
                - post_id
        '404':
          description: pet not found
  "/api/users/:id/posts":
    get:
      summary: displays users posts
      tags:
      - Posts
      parameters: []
      responses:
        '201':
          description: post created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
              required:
              - id
          application/xml:
            schema:
              type: object
              properties:
                id:
                  type: integer
              required:
              - id
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
